### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by leon-fong** [leon-fong/create-wow-app#1]
## Milestone 1: Basic 
- **Goal:** Implement basic command or Inquirer to create an app
- **Key Features Needed:**
	- [X] Basic command (dir/template) support
	- [X] Basic Inquirer (dir/template) support
	- [X] Copy files from basic templates

## Milestone 2: Advanced 
- **Goal:** Enhance stability 
- **Key Features Needed:**
	- [ ] Fix edge issue
	- [ ] Various type of project template support 

## Milestone 3: Complete 
- **Goal:** Implement multiple ways to create an app
- **Key Features Needed:**
	- [ ] Refactor project using monorepo
	- [ ] Build a website to facilitate getting started
	- [ ] Ship a Raycast extension  to simplify getting started
